[tool.black]
line-length = 119
target-version = ['py37', 'py38']
extend-exclude = '''
                      kachra
                    | logger
                    | stubs
                    | tests
                    | trading_freedom_delete
                    | tutorial
                 '''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 90


#[tool.coverage.run]
#command_line = "-m pytest"
#omit = [
#    "*/tests/*",
#    "*/virtualenvs/*",
#    ]
#
#[tool.coverage.report]
#fail_under = 90.0
#skip_empty = true
#show_missing = true